#!/bin/bash

set -e

usage() {
  echo "Usage: $0 [--validate]"
}

case "$#" in
  0) ;; # noop
  1)
    case "$1" in
      --help|-h) usage; exit;;
      --validate) validate=1;;
      *)
        >&2 echo "Unexpected argument: $1"
        >&2 usage
        exit 1
        ;;
    esac
    ;;
  *)
    >&2 echo "Invalid arguments"
    >&2 usage
    exit 1
    ;;
esac

cd "$(dirname $0)/.."

version=$(cat version.txt)

subprojects=(. aeson)

packageYamlHeader() {
  local subproject=$1
  cat <<HERE > "$tmp"
# GENERATED HEADER START
name:                $(name "$subproject")
version:             $version
github:              "estatico/generic-override"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 Estatico Studios LLC"
category:            Generics
description:         Please see the README on GitHub at <https://github.com/estatico/generic-override#readme>
# GENERATED HEADER END
HERE
}

name() {
  local subproject=$1
  if [ "$subproject" = '.' ]; then
    echo 'generic-override'
  else
    echo "generic-override-$subproject"
  fi
}

for subproject in "${subprojects[@]}"; do
  tmp=$(mktemp)
  packageYamlHeader "$subproject" > "$tmp"
  grep -F -A9999 '# GENERATED HEADER END' "$subproject/package.yaml" \
    | tail -n+2 >> "$tmp"
  if [ -n "$validate" ]; then
    if ! diff -u "$subproject/package.yaml" "$tmp"; then
      >&2 echo "Failed validation: $subproject/package.yaml"
      exit 1
    fi
  else
    mv "$tmp" "$subproject/package.yaml"
  fi
done
