#!/bin/bash

set -e

cd "$(dirname $0)/.."

version=$(cat version.txt)

subprojects=(. aeson)

packageYamlHeader() {
  local subproject=$1
  cat <<HERE > "$tmp"
# GENERATED HEADER START
name:                $(name "$subproject")
version:             $version
github:              "estatico/generic-override"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 Estatico Studios LLC"
category:            Generics
description:         Please see the README on GitHub at <https://github.com/estatico/generic-override#readme>
# GENERATED HEADER END
HERE
}

name() {
  local subproject=$1
  if [ "$subproject" = '.' ]; then
    echo 'generic-override'
  else
    echo "generic-override-$subproject"
  fi
}

for subproject in "${subprojects[@]}"; do
  tmp=$(mktemp)
  packageYamlHeader "$subproject" > "$tmp"
  grep -F -A9999 '# GENERATED HEADER END' "$subproject/package.yaml" \
    | tail -n+2 >> "$tmp"
  mv "$tmp" "$subproject/package.yaml"
done
